### ISSUE TITLE
Error with Blizzard_ChallengesUI

### ISSUE THREAD

**Issue by gaveer** [Ironii/iKeystones#3]
i think there is conflict with Blizzard challenges UI 
screen shot with addone **on** 
![image](https://user-images.githubusercontent.com/45834601/96054381-d6aa7f00-0e81-11eb-8971-bc595f1729cc.png)
Screen shot with addone **off** 
![image](https://user-images.githubusercontent.com/45834601/96309122-fcac5c80-1004-11eb-9b09-f7804bee0820.png)

```cs
100x dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:225: attempt to index field '?' (a nil value)
[string @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:225: in function `ChallengesFrame_Update'
[string @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:134: in function <...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:125>
```

**Comment by gaveer** [comment]
https://github.com/Gethe/wow-ui-source/blob/1cf759abedf90eaf4adaa1be3629855626c2d998/AddOns/Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua#L134

**Comment by gaveer** [comment]
any news about this error @Ironii  ?

**Comment by Ironii** [comment]
do you get that error often or always at the specific situation? I got that error once and it seemed more like a default ui bug than anything else (something to do with getting wrong (character) data from the server, seems like it happens quite a bit atm)

**Comment by gaveer** [comment]
i got it everytime i log a character

**Comment by Ironii** [comment]
turns out that force loading Blizzard_ChallengesUI before loading screen was over, would cause it to error out, when its fresh login (per exe launch) on a character that has completed at least one mythic+ this week.
Fixed on the newest version

**Comment by gaveer** [comment]
Ty 💯
